name: Android Build Validation

on:
  pull_request:
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: List directory contents
      run: ls -R
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./android

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./android

    - name: Run tests
      run: ./gradlew test
      working-directory: ./android

    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: android/app/build/reports
